// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Cppspear
NumericMatrix Cppspear(NumericMatrix xinmatrix, NumericMatrix yinmatrix);
RcppExport SEXP LINC_Cppspear(SEXP xinmatrixSEXP, SEXP yinmatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type xinmatrix(xinmatrixSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type yinmatrix(yinmatrixSEXP);
    __result = Rcpp::wrap(Cppspear(xinmatrix, yinmatrix));
    return __result;
END_RCPP
}
// docdd
NumericMatrix docdd(NumericMatrix inmatrix, NumericMatrix outmatrix, double th);
RcppExport SEXP LINC_docdd(SEXP inmatrixSEXP, SEXP outmatrixSEXP, SEXP thSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type inmatrix(inmatrixSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type outmatrix(outmatrixSEXP);
    Rcpp::traits::input_parameter< double >::type th(thSEXP);
    __result = Rcpp::wrap(docdd(inmatrix, outmatrix, th));
    return __result;
END_RCPP
}
// doesd
NumericVector doesd(NumericVector query, NumericVector wquery, int rmax, NumericVector querypos, NumericVector rmaxvec, NumericVector mdiff, double alpha);
RcppExport SEXP LINC_doesd(SEXP querySEXP, SEXP wquerySEXP, SEXP rmaxSEXP, SEXP queryposSEXP, SEXP rmaxvecSEXP, SEXP mdiffSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type query(querySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wquery(wquerySEXP);
    Rcpp::traits::input_parameter< int >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type querypos(queryposSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rmaxvec(rmaxvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mdiff(mdiffSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(doesd(query, wquery, rmax, querypos, rmaxvec, mdiff, alpha));
    return __result;
END_RCPP
}
