// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP LINC_Cppspear(SEXP xinmatrixSEXP, SEXP yinmatrixSEXP);
SEXP LINC_docdd(SEXP inmatrixSEXP, SEXP outmatrixSEXP, SEXP thSEXP);
SEXP LINC_doesd(SEXP querySEXP, SEXP wquerySEXP, SEXP rmaxSEXP, SEXP queryposSEXP, SEXP rmaxvecSEXP, SEXP mdiffSEXP, SEXP alphaSEXP);

R_CallMethodDef callMethods[]  = {
  {"LINC_Cppspear", (DL_FUNC) &LINC_Cppspear, 2},
  {"LINC_docdd", (DL_FUNC) &LINC_docdd, 3},
  {"LINC_doesd", (DL_FUNC) &LINC_doesd, 7},
  {NULL, NULL, 0}
};

void R_init_LINC(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

