# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cppspear <- function(xinmatrix, yinmatrix) {
    .Call('LINC_Cppspear', PACKAGE = 'LINC', xinmatrix, yinmatrix)
}

docdd <- function(inmatrix, outmatrix, th) {
    .Call('LINC_docdd', PACKAGE = 'LINC', inmatrix, outmatrix, th)
}

doesd <- function(query, wquery, rmax, querypos, rmaxvec, mdiff, alpha) {
    .Call('LINC_doesd', PACKAGE = 'LINC', query, wquery, rmax, querypos, rmaxvec, mdiff, alpha)
}

